name: Build Tauri App for Windows

on:
  push:
    branches: [v0.1.0]
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./your-react-folder  # 修改为你的前端目录

      - name: Build frontend
        run: pnpm build
        working-directory: ./your-react-folder  # 修改为你的前端目录

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App (EXE/MSI)
        run: pnpm tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-build
          path: src-tauri/target/release/bundle
